version: '3.3'

services:
  vs-mysql:
    image: mysql:5.7.28
    volumes:
      - ${WEBAPP_STORAGE_HOME}/vs-mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: vs4tw
      MYSQL_DATABASE: vs1
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser

  vs-payara:
    image: hftm/vs-payara-example
    ports:
      - 80:8080
      - 443:4848 
    depends_on:
      - vs-mysql
